### ISSUE TITLE
Support for OBS

### ISSUE THREAD

**Issue by chrisspiegl** [aaronpk/live-chat-overlay#20]
Hello @aaronpk, I heard you mentioned you'd like to make a version of this that is compatible with OBS.

@steveseguin built one which can be viewed at: https://github.com/steveseguin/twitch-youtube-chat-overlay-without-window-capture

Maybe it'd be interesting to merge these two projects and built together upon that foundation?

The version from Steve is built around some socket.io and sends the comments through a server. Customizable layout for how it ends up showing up in the browser source also supported by doing ones own html file.

**Comment by aaronpk** [comment]
The code for this is already in this repo! I have just been waiting to publish the update to the Chrome store until I've done a bit more testing with it. So far it's been working well though so I'm just about ready! If you want to try it out, download the code from this repo and use the "load unpacked" installation option.

**Comment by chrisspiegl** [comment]
I'm gonna wait for the release for now 👍.
But it's gonna be a great improvement to be able to do this.

**Comment by aaronpk** [comment]
This is released now! If your extension is auto-updated you should have a new "Get Overlay URL" button on the popout chat page!

**Comment by chrisspiegl** [comment]
@aaronpk Question about the way you implemented this:
Does this method also have the ability to change the message style / have a custom html file for the receiving side like the one from @steveseguin does?

**Comment by aaronpk** [comment]
Not quite in this iteration, since actually it's still the browser extension that builds the HTML. My next plan (#22) is to refactor it so that only the chat message data itself is sent to the remote end that way you can host a custom HTML page for more flexibility there too.

**Comment by chrisspiegl** [comment]
@aaronpk Great to hear. I started playing around with Steves solution and built my own transitions and all that's why I am asking.

Gonna be interesting what comes out of these extensions for lower third comment integration 👍.
