### ISSUE TITLE
The Extension does not give the URL to OBS due to an error HELP

### ISSUE THREAD

**Issue by vimaesar** [aaronpk/live-chat-overlay#21]
![error live chat extension](https://user-images.githubusercontent.com/86861945/124340173-d9b4df00-db78-11eb-8fc4-5cf3c97c7759.png)

Unrecognized manifest key 'browser_specific_settings'.

{
  "name": "Live Chat Overlay",
  "description": "Restyle the YouTube popout chat so you can overlay it for livestreams",
  "manifest_version": 2,
  "version": "0.2.1",
  "homepage_url": "https://github.com/aaronpk/YouTube-Chat-Overlay",
  "icons": {
    "128": "icons/icon-128.png"
  },
  "permissions": [
    "https://youtube.com/*", "https://www.youtube.com/*", "https://studio.youtube.com/*", "storage"
  ],
  "content_scripts": [{
    "css": ["youtube.css"],
    "js": ["jquery.js", "youtube.js"],
    "matches": ["https://youtube.com/live_chat*", "https://www.youtube.com/live_chat*", "https://studio.youtube.com/live_chat*"]
  }],
  "options_ui": {
    "page": "settings/options.html"
  },
  "browser_specific_settings": {
    "gecko": {
      "id": "live-chat-overlay@aaronpk.tv",
      "strict_min_version": "80.0"
    }

Could you help me please?

**Comment by aaronpk** [comment]
This doesn't actually prevent anything from working as far as I can tell. This is a field that Firefox needs for the extension that google doesn't know about. 

What happens when you try to get the overlay URL?

**Comment by vimaesar** [comment]
![image](https://user-images.githubusercontent.com/86861945/124345284-9a4cb980-db9d-11eb-9cf5-fde87c6601ef.png)
 I use Google Chrome

**Comment by aaronpk** [comment]
Thank you for the screenshot! I will fix this ASAP

**Comment by aaronpk** [comment]
This has been fixed in version 0.2.2 which is currently live! Thanks!

**Comment by vimaesar** [comment]
Thank you!!!
