### ISSUE TITLE
Word wrap...

### ISSUE THREAD

**Issue by ScrubDonkey** [aaronpk/live-chat-overlay#32]
One thing I notice is at least for me. There is no word wrap functioning. So everything just trails off on a single line not wrapping to a new line. Any ideas?

**Comment by aaronpk** [comment]
It should wrap depending on the size of the window. However depending on your font size, the end of messages might be getting cut off. I don't have a good solution for that other than tweaking the size of the font in the settings if you regularly get long messages.
