### ISSUE TITLE
Chat will only show up if i clicked one of the chat message.

### ISSUE THREAD

**Issue by Putu-Justine** [aaronpk/live-chat-overlay#37]
first of all, nice extensions.

Well, the title says it all. the chat will only show up on the overlay link IF i click one of the chat message.

**Comment by Putu-Justine** [comment]
Video as a proof

https://user-images.githubusercontent.com/63581135/187063480-53d34072-8090-4395-9ae6-e784cd484430.mp4

**Comment by aaronpk** [comment]
Yes, this is by design, this is how it's supposed to work.
