### ISSUE TITLE
Chat instantly disappears when it pops up

### ISSUE THREAD

**Issue by raynexero** [aaronpk/live-chat-overlay#38]
So when I click on a chat bubble, it will briefly appear on my screen and then disappear a split second later
I thought that the new setting would be the issue, but even after setting it to 0 or 9999999999 the chat still disappears the moment it comes up. It's there for like a split second tops before it's gone again

I reinstalled the extension just to be safe, but this still doesn't fix it.
Updated OBS as well, but no dice

Please help! Am I being dumb?

**Comment by carlsgithub** [comment]
Came here for the same reason. hoping to get some help.

**Comment by aaronpk** [comment]
I'm fixing this in the next update. In the mean time, go into the settings and change the auto-hide timeout to 10 seconds or so.

**Comment by carlsgithub** [comment]
> I'm fixing this in the next update. In the mean time, go into the settings and change the auto-hide timeout to 10 seconds or so.

FYI: It works on Edge still.

**Comment by aaronpk** [comment]
Fixed in a0415726c489c6cb0dd4e069abcc89575c9dffe6

This release is pending review by the Chrome extension team now
