### ISSUE TITLE
Member Milestone Chat Issue

### ISSUE THREAD

**Issue by swhatl** [aaronpk/live-chat-overlay#40]
There is an issue when channel members use their monthly "milestone chat". It incorrectly displays the "New Member" badge.  

![Screen Shot 2022-10-04 at 4 25 43 PM](https://user-images.githubusercontent.com/115041991/193919805-a98a891b-457e-4725-b3b9-0a036cd2c6e3.png)

**Comment by aaronpk** [comment]
oh thank you! I didn't even know that was an option!

To fix this, I need to see this happen live so I can look at the HTML. Do you have a way to test this when I could take a look at it? Alternatively, do you know how to use the inspector in Chrome to copy HTML?

**Comment by aaronpk** [comment]
This has been fixed in ade78e0125c0324e3336b7eb66200f05fd8e2bd2
