### ISSUE TITLE
Get Overlay URL stopped working

### ISSUE THREAD

**Issue by clarkezone** [aaronpk/live-chat-overlay#41]
I was playing with the live chat overlay extension this evening and it was working well until it stopped :-). From studio, i pop out the chat window and see things working fine as shown in these two screenshots:

<img width="1059" alt="Screenshot 2022-12-01 at 9 45 26 PM" src="https://user-images.githubusercontent.com/1128250/205223636-46b3c99a-03d7-4fda-a551-2b472705736b.png">

and

<img width="1059" alt="Screenshot 2022-12-01 at 9 47 00 PM" src="https://user-images.githubusercontent.com/1128250/205223818-38da7458-be22-43d0-8bd1-b858644571d0.png">

When I click on Get Overlay (in order to get something I can key using OBS with Ultrastudio) i see no output in the modified page:
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/1128250/205224362-736b87c1-06c9-4281-af62-6773eded7826.png">

of by following the URL:
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/1128250/205224627-6b6eda16-0496-4ae1-92cb-cf9400c44be6.png">

This was working earlier so I hope I haven't tripped a rate limit.  Any ideas greatly received :-)

Thx Aaron

**Comment by aaronpk** [comment]
Strange, I don't see anything wrong.

In your screenshots, you have two separate session IDs (the part after the `#`). Is that just an artifact of testing it a few times? Or maybe that's the problem? It looks like the browser window you opened separately is not the same URL as the one showing in the screenshot of the youtube chat.

**Comment by clarkezone** [comment]
Captured over the course of multiple tests.  I confirmed it was still repealing yesterday after your live stream.  Wondering if there is anything I could look at in browser tools or if there is a pointer to building and debugging the extensions

**Comment by aaronpk** [comment]
Checking the JavaScript console for errors would be a good start. You should be able to go to View -> Developer -> JavaScript console. Then click around and see if any errors pop up.

**Comment by clarkezone** [comment]
Debugging the working path, looks like line 113 in `youtube.js` is what's doing the jquery `append(html)` operation.. in the working case i see a breakpoint hit on `next()` after the chain of actions including the delay containing a closure:

![image](https://user-images.githubusercontent.com/1128250/205785708-9bf4f996-2f26-4f09-ae48-768db321be18.png)

In the non-working case, looks like the code is going down the `if(sessionID)` branch (line 102) instead of the `else` where the above `append(html)` lives and never entering the else branch that would be adding something to the DOM:

![image](https://user-images.githubusercontent.com/1128250/205786010-a8b0c721-375d-4f9a-9312-75f4a30989d9.png)

although if i patch `sessionID` to be empty in the console, forcing the code to go down the jquery `append` path, execution never gets to `next()` as it does in the working case.  Unfortunately debugging in to the chain of actions in minified jquery source wasn't particularly fruitful to find a root cause for the failure.

Does this give you more to go on?

**Comment by aaronpk** [comment]
So the sessionID is what switches between showing the comment in the same window vs showing in the remote view. If you're opening the overlay url you should see it make that post request on line 109. That sends the message to my server which renders it in the chat.aaronpk.tv website. Once you click get overlay url it will stop showing the comment in your YouTube window since it's sending it to the remote server instead. Are you really not seeing the message on the chat.aaronpk.tv page when you click it in your YouTube chat window? Do you have any firewall thing that might be blocking the request? I'm seeing lots of other messages going through right now so I'm wondering if this is something specific to your environment that we can troubleshoot more.

**Comment by clarkezone** [comment]
I do see posts although hard to tell if they succeed or fail.. here's an example of an active url: https://chat.aaronpk.tv/overlay/#XVvkjs5Tnn and here is the url that the post function is trying to send:
https://chat.aaronpk.tv/overlay/pub?id=XVvkjs5Tnn

What's weird is that it was working fine for a bit on Saturday on multiple machines and then stopped, nothing I can think of at this end changes.  I do use Tailscale on all my devices but that should only come into play for calls between devices on the tailnet.  To rule that out have tried with it disabled.  I'm seeing the same thing in both Chrome and Brave.  I have a Ubiquity UDM pro, no fancy firewall settings.

**Comment by aaronpk** [comment]
Do you have a minute for a zoom call? I think this is going to take some synchronous debugging

**Comment by aaronpk** [comment]
https://us06web.zoom.us/j/5035678642
