### ISSUE TITLE
Get Overlay has also stopped working for me

### ISSUE THREAD

**Issue by vk-dmalenda** [aaronpk/live-chat-overlay#42]
When I click on the Get Overlay button instead of getting the usual chat.aaronpk.... url and link... it now is just the pop-out youtube url with an additional anchor appended to it [which I tried using to no avail].

This is a VERY awesome module and I use it all the time, happy to support a Patreon if you set one up just to keep this thing running and up to date!

**Comment by aaronpk** [comment]
I don't see anything wrong with it, I tested the "Get Overlay URL" button and it worked fine. 

Could you open the browser console and see if there are any errors reported? From the Chrome window, click View -> Developer -> JavaScript Console and paste a screenshot of what you see.

**Comment by vk-dmalenda** [comment]
Aaron,

I appreciate you taking any time to look into this for me; let me know if you have a ko-fi link or something I can help you out with!

There seems to be a 400 status error being returned from the server?

Additionally when I click on the "Overlay URL" button, I am used to getting a URL to your server, but now it just returns a studio.youtube.... url


![LiveChatOverlay Console](https://user-images.githubusercontent.com/100156654/205831417-18b76614-98bf-4b3b-b76f-3b1f482da584.JPG)
![LiveChatOverlay youtube popout chat](https://user-images.githubusercontent.com/100156654/205831476-3fb71d9b-e4af-4ef8-a6e1-a7a4f346d772.JPG)
![livechat overlay after push button](https://user-images.githubusercontent.com/100156654/205831497-9b6fe49e-1cf9-4f23-824a-12f45621ec8b.JPG)

**Comment by ChilliChump** [comment]
@vk-dmalenda My guess is that you have changed the URL in the settings for the extension.  Go to the settings for the extension, and scroll towards the bottom. Make sure the "Popout Chat URL" is set to https://chat.aaronpk.tv/overlay/

**Comment by aaronpk** [comment]
Thanks @ChilliChump yes that looks like what happened, since we shouldn't be seeing that "studio.youtube.com" URL in the screenshot.
