### ISSUE TITLE
New Remote Server URL option not saved

### ISSUE THREAD

**Issue by pedanticdan** [aaronpk/live-chat-overlay#43]
I’ve briefly got my own server to work. While debugging I found that Chrome automatically updated the plugin. If I change the URLs in the options settings, the Remote Server URL is not saved (or saved, but not restored).

I forked the repo and found that adding “serverURL” to the properties list on line 26 of options.js fixed that problem.

[EDIT] And adding "serverURL" to configProperties on line 206 of youtube.js fixed my last problem, which was that that chat.aaronpk.tv was always used for the serverURL not matter what the option was set to.

**Comment by aaronpk** [comment]
Fixed in #44, thanks!
