### ISSUE TITLE
Options appearing everytime you click on a comment when chat is popped out

### ISSUE THREAD

**Issue by RidiculocitY** [aaronpk/live-chat-overlay#46]
Hi there, For the last week everytime I pop out the chat for a live stream and click a comment it appears on my stream but in the chat window the moderator options pop up also covering most of the chat. It's made the chat impossible to see. any way to fix this in an update soon?
![chat issue](https://user-images.githubusercontent.com/128961105/227762450-3985b921-02cc-4750-a3bd-4c89008b63b2.jpg)

**Comment by aaronpk** [comment]
Well that's annoying, they must have changed something in the YouTube UI. I will take a look and try to fix it!

**Comment by RidiculocitY** [comment]
Wow thank you for the quick response. I don't know what I'd do without your amazing extension.

**Comment by aaronpk** [comment]
I'm testing this out right now, and this isn't happening for me. I'm using Chrome on a Mac. What browser/OS are you using?

Just to clarify, when does the moderator menu pop up? Is it in response to you clicking on a chat message?

Could you maybe record a little screen recording so I can see what's happening better?

**Comment by RidiculocitY** [comment]
I'm using PC windows 10 Chrome browser Version 111.0.5563.111 (Official Build) (64-bit)
Yes every time I click on a message it pops up and wont go away till I click on the scroll bar or am able to click the clear button.

I know 2 other streamers who are using it and its happening for them also on a PC and MAC
https://user-images.githubusercontent.com/128961105/227768456-70fc75b7-e956-4fc3-a5ba-07bf807cef62.mp4

**Comment by aaronpk** [comment]
I've been testing this out and unfortunately haven't been able to reproduce this myself. I'm going to have to see if anyone else has a suggestion about why this might be happening.

In the mean time, I started working on an option that will let you remove the moderation menu for chat lines entirely. Unfortunately, I have only been able to get that to work for new chat lines added, but if you reload the page in the middle of a stream, any of the first chat lines that load will still have the menu.

I don't think this is good enough to release right now, but if you want to try it out, you can follow the [manual install instructions](https://github.com/aaronpk/live-chat-overlay#manual-installation).

**Comment by RidiculocitY** [comment]
Cheers. Thank you. I'll wait till you find a proper solution. I wonder why you cant recreate it. As I said one of my friends channels uses a mac and OBS and he had the same problem and another girl I know experienced the same this this weekend on her stream and shes on a pc and obs. Hopefully you can sort it out. Thank you for being so prompt. I must sleep now its late here in Australia

**Comment by RidiculocitY** [comment]
Any update on this issue?

**Comment by DoubleMunch** [comment]
Same problem here.

**Comment by aaronpk** [comment]
Sorry, I still haven't been able to figure out what's going on. Anyone else having this problem?

**Comment by RidiculocitY** [comment]
It's been working fine the last 3 weeks

**Comment by aaronpk** [comment]
oh good, glad to hear it. Perhaps it was a momentary change on YouTube's side then. I'll close the issue but feel free to open a new issue if it starts happening again.
