### ISSUE TITLE
Problem with Live Streaming and Live Chat (Slowdown)

### ISSUE THREAD

**Issue by Geilor** [aaronpk/live-chat-overlay#47]
Hello there, I don't know if this is a common issue. We experienced while having our live cast slow downs and transmission problems, everytime the google chat window wasn't on top. That means, if I had OBS in front of the google window, our video lagged.

You can see it here at 4:12 for example:

https://www.youtube.com/watch?v=JR0bm54hHc0

Maybe you can help us.

**Comment by aaronpk** [comment]
Sorry, I have no idea what would be causing this, but I doubt it's anything related to this extension.
