### ISSUE TITLE
Chat no longer working in OBS

### ISSUE THREAD

**Issue by RidiculocitY** [aaronpk/live-chat-overlay#48]
Hi I set up for my stream today and the chats are no longer appearing on the screen in OBS

**Comment by aaronpk** [comment]
I'm not seeing anything wrong on my end, can you try loading the popout URL in a browser outside of OBS and see if the messages appear there? That will help track down whether it's a problem with OBS specifically or something larger.

**Comment by RidiculocitY** [comment]
Yes it is working in the browser. But not in obs. I havent updated obs or changed anything overnight since my last stream. I'm still on obs 27.2.4

**Comment by aaronpk** [comment]
ok sorry I just double checked and I did see some errors on the server. try now, it should be working again.

**Comment by RidiculocitY** [comment]
Perfect! Thank you all working good now. you rock!!!
