### ISSUE TITLE
OBS panels

### ISSUE THREAD

**Issue by oDiegoFortes** [aaronpk/live-chat-overlay#49]
Good morning everyone... I saw a good idea while using this amazing chat!

It would be great if we had a "dashboard" in a url to use within the OBS panels, thus saving the pc's memory, since I wouldn't need to keep the browser open!

I don't know the complexity of this, but it is something that could be an excellent upgrade!

This text was written with the help of google translator, I apologize for any errors!

**Comment by aaronpk** [comment]
I'm not entirely sure what you're asking for, but I suspect it's not doable with this extension. A "proper" solution would use the YouTube API to pull chat messages, and then you could create whatever kind of dashboard you want, but this is limited to running inside the actual YouTube popout chat window.
