### ISSUE TITLE
Persistent Links

### ISSUE THREAD

**Issue by profcaju** [aaronpk/live-chat-overlay#51]
In the readme.md there is a text saying that the extension now support for persistent link, and that the options of the extension should have a "Persistent Session ID" check box, but I could not find this option in my options list. I am using 0.3.6 version (latest), and just have the following options:

![image](https://github.com/aaronpk/live-chat-overlay/assets/24816099/9f04e486-1468-442a-97b8-1d7dbb98a9f7)
![image](https://github.com/aaronpk/live-chat-overlay/assets/24816099/f75cbdd9-f421-4d52-ab6b-a7c199530e50)

Am I missing something?

**Comment by aaronpk** [comment]
Apparently I haven't pushed this out to the Chrome store yet. I'll get this updated today.
