### ISSUE TITLE
Remote Server URL won't save

### ISSUE THREAD

**Issue by whizkidTRW** [aaronpk/live-chat-overlay#52]
I'm trying to use a locally hosted overlay server so that I can customize the behavior of the message and trigger the parent iframe holding the overlay to automatically dim the background (I'm using it teleprompter style to show on-air talent comments before putting them over the livestream). 

But, before getting into any of that, I'm just trying to get the local server to work. I have NGINX all installed and working, but I can't get the Chrome plugin to save the Remote Server URL setting. The Popout Chat URL setting saves just fine.

Help!

**Comment by aaronpk** [comment]
Sorry for the trouble. This was fixed in ddc1a05ec1d6b591a05fe2f904f1165de6a7a7ef and will go out in the next update.

**Comment by whizkidTRW** [comment]
Thanks Aaron!
