### ISSUE TITLE
Scrollbar disappears 

### ISSUE THREAD

**Issue by lost-packet** [aaronpk/live-chat-overlay#57]
Just tried this plugin, awesome work. Works at first butbthen chat seems to stop updating and scrollbar disappears.

**Comment by lost-packet** [comment]
Think ibwas doing it wrong

**Comment by lost-packet** [comment]
Doesn't seem to be me after all, scollbars disapper so can scroll down snd three dots to right are not show where uou can remove pepplenfrom chat. Windows 11 if that makes a difference

**Comment by aaronpk** [comment]
ok shoot I will take a look. I can't imagine what is going on here though!

**Comment by aaronpk** [comment]
It looks like the scrollbar is actually moving to scroll the little dropdown menu with the "report/block" buttons, but if you hit escape, it closes that out and restores the scrollbar to the main window

**Comment by lost-packet** [comment]
If i click on a message in the window it briefly shows the dropdown, then highlights green, at which point the scrollbar disappears. Clicking clear clears message on obs but still shows highlted green with no scrollbar.

Only thing i can do is f5 to refresh the page, then have same issue everytime i click on a message and have to press f5 again to get scrollbars back.

I hate windows 11 😀

**Comment by aaronpk** [comment]
does the "clear" button restore the scrollbar?

**Comment by aaronpk** [comment]
ok this is weird, it's not just you, it's not me, and it's not the extension. I just loaded up a livestream chat in safari where this extension isn't installed, and I'm seeing even worse behavior.

If I click on a message in safari, the dropdown menu doesn't appear, but the scrollbar does disappear. If I press escape the scrollbar re-appears.

**Comment by lost-packet** [comment]
If you right click the scrollbar and inspect it before clicking anything, you can see there's "overflow-y: hidden" crossed out, but when you click on a message and then inspect the scrollbar, the "overflow-y: hidden" is no longer crossed out and being applied:

#item-scroller.yt-live-chat-item-list-renderer {
    flex: 1;
    flex-basis: 1e-9px;
    overflow-x: hidden;
    overflow-y: hidden;     <------ this line here, hidden becomes active on clicking
    padding-right: var(--scrollbar-width);
    overflow-anchor: none;
}

**Comment by aaronpk** [comment]
That's youtube's own javascript doing that, not my code. It's looking like youtube made a change that's causing this. I'm trying to work around it now.

**Comment by lost-packet** [comment]
Temp work around unchecking thaf property makes usable until page refresh.

**Comment by aaronpk** [comment]
Ok cool, I tried adding that to the extension CSS, and it kind of worked. The scroll bar doesn't disappear anymore, and I can drag it, but I can't use the scroll gesture with the mouse anymore. I don't think that's a good solution to ship in the extension unfortunately.

**Comment by lost-packet** [comment]
also looses the ability to remove comments, the 3 dots dissappear

**Comment by aaronpk** [comment]
ok I think I fixed it, I'm going to push this out right now because it's definitely broken for everyone not just you.

This does hide the moderation menu completely, but I am okay with that. If you need to, keep the comments open in youtube studio and moderate them there.

**Comment by aaronpk** [comment]
Fixed in be44163fc7aa5201127e839a925bfbb431466240

Thank you for reporting this!

**Comment by lost-packet** [comment]
If you don't apply the green highlight to the highlighted comment does it make a difference?

**Comment by aaronpk** [comment]
no, that's unrelated
