### ISSUE TITLE
was working now getting bad gateway and grey line through my screen

### ISSUE THREAD

**Issue by stevecarty** [aaronpk/live-chat-overlay#59]
hey crew. i've been a user for almost 3 years. have had zero issues. 
today i'm getting bad gateway and a black line through my browser source in obw.

![Screenshot 2024-05-21 at 5 50 19 PM](https://github.com/aaronpk/live-chat-overlay/assets/94952520/d45fcdb0-67e4-4ea1-9058-898e40fb1f59)

any help would be appreciated.

**Comment by aaronpk** [comment]
Sorry, the web host I use is having to do emergency maintenance. It should be back momentarily

**Comment by stevecarty** [comment]
Please lmk when you’re back up.


Carty.

http://SteveCarty.com (portfolio)
http://theCartyMethod.com (education)
***@***.*** 
CAN +1-416-822-7521
@stevecarty (all socials)

Become a Smarter Pro Photographer in just 5 minutes.
http://stevecarty.substack.com

**Comment by aaronpk** [comment]
oh sorry, it was back up as of yesterday around 7pm pacific time or so. Sorry for the inconvenience!
