### ISSUE TITLE
Live Chat Overlay - Android & IOS

### ISSUE THREAD

**Issue by Pomfus** [aaronpk/live-chat-overlay#63]
Hi there,

Is there a way to install the extension on Ipad or Android?  I have it installed on Google Chrome on my PC, and that is synched with my Ipad/Android but it wont work or recognise that the extension is on there.

**Comment by aaronpk** [comment]
It's definitely not as simple as on desktop, but I just searched for how to install chrome extensions on Android and found this thread with some interesting ideas: https://www.reddit.com/r/browsers/comments/1acxbvy/any_way_to_install_extensions_on_chrome_for/
